export const TRACKS = [
  { id: "none", name: "재생 안 함 (무음)", artist: "-" },
  { id: "song_1", name: "여행", artist: "볼빨간사춘기" },
  { id: "song_2", name: "Love Lee", artist: "악동 뮤지션" },
  { id: "song_3", name: "바이,썸머", artist: "아이유" },
  { id: "song_4", name: "Ai Wo Tsutaetaidatoka", artist: "아이묭" },
  { id: "song_5", name: "사계 - 봄", artist: "비발디" },
  { id: "song_6", name: "숲", artist: "최유리" },
  { id: "song_7", name: "salty", artist: "데이먼스이어" },
  { id: "song_8", name: "서울의 잠 못 이루는 밤", artist: "10CM X 이수현" },
  { id: "song_9", name: "언제라도 어디에서라도", artist: "정승환" },
  { id: "song_10", name: "사계 - 가을", artist: "비발디" },
  { id: "song_11", name: "비", artist: "폴킴" },
  { id: "song_12", name: "소나기", artist: "이클립스" },
  { id: "song_13", name: "잠 못 드는 밤 비는 내리고", artist: "아이유" },
  { id: "song_14", name: "비 오는날 듣기좋은 노래", artist: "에픽하이" },
  { id: "song_15", name: "사계 - 여름", artist: "비발디" },
  { id: "song_16", name: "첫 눈", artist: "EXO" },
  { id: "song_17", name: "겨울잠", artist: "아이유" },
  { id: "song_18", name: "첫 눈처럼 너에게 가겠다", artist: "에일리" },
  { id: "song_19", name: "눈사람", artist: "정승환" },
  { id: "song_20", name: "사계 - 겨울", artist: "비발디" },
  { id: "song_21", name: "킬링벌스", artist: "창모" },
  { id: "song_22", name: "밤바다", artist: "최유리" },
  { id: "song_23", name: "round and round", artist: "jisokury" },
  { id: "song_24", name: "lemon tree", artist: "정예원" },
  { id: "song_25", name: "그때가좋았어", artist: "oysters" },
  { id: "song_26", name: "0026 짧은노래", artist: "테스트 음원" },
];
